name: Node.js CI

on:
  push:
    paths-ignore:
    - 'README.MD'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gif-email-bot
    strategy:
      matrix:
        node-version: [16.x]
    env:
      API_KEY: ${{ secrets.API_KEY }}
      TEST: ${{ secrets.TEST }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: send email
      run: |
        echo "Test" $TEST
        curl -H "X-API-KEY: Bearer: $API_KEY" https://gif-bot.netlify.app/.netlify/functions/sendEmails