name: daily-cron
on:
  schedule:
    - cron: '45 5 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    environment: gif-email-bot
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: send email
        run: |
          curl -H "X-API-KEY: Bearer: $API_KEY" https://gif-bot.netlify.app/.netlify/functions/sendEmails
