name: daily-cron
on:
  schedule:
    - cron: '45 5 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: send email
        run: |
          curl -H "X-API-KEY: Bearer: ${{ secrets.API_KEY }}" https://gif-bot.netlify.app/.netlify/functions/sendEmails